package update

// seam E 换装目标解析(票05):解析 start-daemon.cmd 引号内 exe 路径;解析失败
// 回落 os.Executable()。测试自建 cmd 文件(installer.EnsureLauncher 同形态,
// 外加 set 行干扰),绝不读 ~/ferryman 真身。

import (
	"os"
	"path/filepath"
	"testing"
)

// writeCmdFile 造一份点火脚本(EnsureLauncher 同形态;可选附加行)。
func writeCmdFile(t *testing.T, dir string, extraLines []string, launchLine string) string {
	t.Helper()
	body := "@echo off\r\n" +
		"rem Ferryman daemon launcher (auto-generated by install-cc, do not edit)\r\n"
	for _, l := range extraLines {
		body += l + "\r\n"
	}
	body += launchLine + "\r\n"
	p := filepath.Join(dir, "start-daemon.cmd")
	if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return p
}

// TestParseStartDaemonExe 生产形态:跳过 @/rem 行;同行的日志重定向引号不误中;
// set 行的引号值(不以 .exe 结尾)不误中;盘上存在才认。
func TestParseStartDaemonExe(t *testing.T) {
	dir := t.TempDir()
	exe := filepath.Join(dir, "ferryman.exe")
	if err := os.WriteFile(exe, []byte("MZ-fake"), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := writeCmdFile(t, dir,
		[]string{"set \"FERRYMAN_STANDIN=1\"", "set \"TOKEN=abc123\""},
		"\""+exe+"\" serve >> \""+filepath.Join(dir, "out.log")+"\" 2>> \""+filepath.Join(dir, "err.log")+"\"")

	got, err := ParseStartDaemonExe(cmd)
	if err != nil {
		t.Fatal(err)
	}
	if !samePath(got, exe) {
		t.Fatalf("解析 = %q, want %q", got, exe)
	}
}

// TestParseStartDaemonExeRejects 解析失败三态:无引号 exe 行 / exe 不存在 /
// 文件本身缺失。
func TestParseStartDaemonExeRejects(t *testing.T) {
	dir := t.TempDir()
	exe := filepath.Join(dir, "ferryman.exe")
	if err := os.WriteFile(exe, []byte("MZ-fake"), 0o644); err != nil {
		t.Fatal(err)
	}

	// 无引号 exe(裸路径无引号形态)→ 失败
	cmd := writeCmdFile(t, dir, nil, exe+" serve")
	if _, err := ParseStartDaemonExe(cmd); err == nil {
		t.Fatalf("无引号形态应解析失败")
	}

	// 引号内路径不存在 → 失败(防指向已挪窝的旧路径)
	ghost := filepath.Join(dir, "ghost.exe")
	cmd = writeCmdFile(t, dir, nil, "\""+ghost+"\" serve")
	if _, err := ParseStartDaemonExe(cmd); err == nil {
		t.Fatalf("exe 不存在应解析失败")
	}

	// 文件本身缺失 → 失败
	if _, err := ParseStartDaemonExe(filepath.Join(dir, "nope.cmd")); err == nil {
		t.Fatalf("cmd 文件缺失应解析失败")
	}
}

// TestResolveSwapTargetFallback seam E 回落:解析失败时回落 os.Executable()。
func TestResolveSwapTargetFallback(t *testing.T) {
	dir := t.TempDir()
	self, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	cmd := writeCmdFile(t, dir, nil, "echo nothing quoted exe here")
	got, err := ResolveSwapTarget(cmd)
	if err != nil {
		t.Fatal(err)
	}
	if !samePath(got, self) {
		t.Fatalf("回落 = %q, want 本进程映像 %q", got, self)
	}
}
